package config

import (
	"bytes"
	"errors"
	"fmt"
	"log"
	"os"
	"regexp"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// EffectiveConfigName is the snapshot of the fully-resolved config the bridge writes to
// its working directory at every startup. It is OUTPUT ONLY — the bridge never reads it
// back — and exists so hosts/users can inspect exactly what the bridge resolved,
// especially when it refuses to start.
const EffectiveConfigName = "bridge.effective.yaml"

// Meta records how the config was resolved; it feeds the effective-config header and
// the startup log lines.
type Meta struct {
	Mode       string // "file" or "env"
	ConfigPath string // the -config path that was checked (may not exist in env mode)
	Forced     bool   // ODB_CONFIG=none is set (env mode guaranteed even if a config file appears)
	FileExists bool   // a file was present at ConfigPath
	Warnings   []string
	Validation error // nil when the config validated OK
}

func (m Meta) modeLine() string {
	switch {
	case m.Mode == "file":
		return fmt.Sprintf("file mode (%s)", m.ConfigPath)
	case m.Forced && m.FileExists:
		return fmt.Sprintf("env-var mode (ODB_CONFIG=none — ignoring existing %q)", m.ConfigPath)
	case m.Forced:
		return fmt.Sprintf("env-var mode (ODB_CONFIG=none; no file at %q either)", m.ConfigPath)
	case m.ConfigPath != "":
		return fmt.Sprintf("env-var mode (no file at %q)", m.ConfigPath)
	default:
		return "env-var mode"
	}
}

// finish is the single tail shared by both config modes: validate, dump the effective
// config (even when validation fails — that's when inspection matters most), and log.
func finish(c *Config, m Meta) (*Config, error) {
	m.Validation = c.validate()
	writeEffective(c, m)
	if m.Validation != nil {
		return nil, m.Validation
	}
	return c, nil
}

// writeEffective renders and writes the effective-config snapshot. Best-effort: failures
// are logged, never fatal.
func writeEffective(c *Config, m Meta) {
	log.Printf("config: %s", m.modeLine())
	for _, w := range m.Warnings {
		log.Printf("config: WARNING: %s", w)
	}
	body, err := renderEffective(c, m)
	if err == nil {
		err = os.WriteFile(EffectiveConfigName, body, 0o644)
	}
	if err != nil {
		log.Printf("config: could not write %s: %v", EffectiveConfigName, err)
		return
	}
	log.Printf("config: effective config written to %s (inspection only, never read back)", EffectiveConfigName)
}

func renderEffective(c *Config, m Meta) ([]byte, error) {
	var sb strings.Builder
	sb.WriteString("# " + EffectiveConfigName + " — auto-generated by open-discord-bridge at every startup.\n")
	sb.WriteString("# OUTPUT ONLY, for inspection/debugging: the bridge never reads this file,\n")
	sb.WriteString("# and edits here have no effect. To configure the bridge, use bridge.yaml or\n")
	sb.WriteString("# environment variables (see bridge.yaml.example).\n#\n")
	fmt.Fprintf(&sb, "# Generated:    %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&sb, "# Config mode:  %s\n", m.modeLine())
	if m.Validation != nil {
		fmt.Fprintf(&sb, "# Validation:   FAILED — %v (the bridge exits when validation fails)\n", m.Validation)
	} else {
		sb.WriteString("# Validation:   OK\n")
	}
	sb.WriteString("# Secrets (values are never written to this file):\n")
	for _, line := range secretLines(c) {
		fmt.Fprintf(&sb, "#   %s\n", line)
	}
	if len(m.Warnings) > 0 {
		sb.WriteString("# Warnings:\n")
		for _, w := range m.Warnings {
			fmt.Fprintf(&sb, "#   - %s\n", w)
		}
	}
	sb.WriteString("\n")

	body, err := yaml.Marshal(c)
	if err != nil {
		return nil, err
	}
	sb.Write(body)
	return []byte(sb.String()), nil
}

// secretLines reports each relevant secret as "ENV_NAME: SET (n chars)" or
// "ENV_NAME: MISSING". Only the env var's name and the value's length appear — the
// length exists to catch truncated/mangled pastes that "SET" alone would hide.
func secretLines(c *Config) []string {
	lines := []string{
		secretLine(c.Discord.TokenEnv, "discord.token_env", c.Discord.Token),
		secretLine(c.Factorio.RCON.PasswordEnv, "factorio.rcon.password_env", c.Factorio.RCON.Password),
	}
	if c.ControlAPI.Enabled {
		lines = append(lines, secretLine(c.ControlAPI.AuthTokenEnv, "control_api.auth_token_env", c.ControlAPI.AuthToken))
	}
	if c.Transport == "sftp" {
		lines = append(lines, secretLine(c.Factorio.SFTP.PasswordEnv, "factorio.sftp.password_env", c.Factorio.SFTP.Password))
	}
	return lines
}

func secretLine(envName, configKey, value string) string {
	name := envName
	if name == "" {
		name = fmt.Sprintf("(%s not set)", configKey)
	}
	if value == "" {
		return name + ": MISSING"
	}
	return fmt.Sprintf("%s: SET (%d chars)", name, len(value))
}

var unknownFieldRe = regexp.MustCompile(`line (\d+): field (\S+) not found in type \S+`)

// unknownKeyWarnings re-decodes the raw YAML in strict mode purely to harvest
// unknown-key warnings. The real decode stays lenient, so stray keys (e.g. a hosting
// panel injecting values at the wrong path) warn loudly instead of bricking the setup.
func unknownKeyWarnings(raw []byte) []string {
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	var probe Config
	err := dec.Decode(&probe)
	if err == nil {
		return nil
	}
	var te *yaml.TypeError
	if !errors.As(err, &te) {
		return nil // non-strictness errors already surfaced by the lenient decode
	}
	var out []string
	for _, e := range te.Errors {
		if mm := unknownFieldRe.FindStringSubmatch(e); mm != nil {
			out = append(out, fmt.Sprintf("line %s: unknown key %q ignored — not part of the bridge config; check the key path", mm[1], mm[2]))
		}
	}
	return out
}
