package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestUpdateRoutesFileRoundTrips covers fix #4: a routing change applied via the Control
// API must survive a restart. UpdateRoutesFile rewrites discord.routes in place and a
// fresh Load of the file must reflect the new routes.
func TestUpdateRoutesFileRoundTrips(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "bridge.yaml")
	original := `# Generated by the Open Discord Bridge setup wizard.
factorio:
  rcon:
    address: game:27015
    password_env: FACTORIO_RCON_PASSWORD
  events_file: /tmp/events.jsonl

transport: local
poll_interval: 1s

discord:
  token_env: DISCORD_BOT_TOKEN
  guild_id: "123"
  routes:
    - source: "*"
      channel_id: "111"
  commands:
    - trigger: "!players"
      rcon: "/players online"
`
	if err := os.WriteFile(path, []byte(original), 0644); err != nil {
		t.Fatalf("write initial config: %v", err)
	}

	newRoutes := []Route{
		{Source: "vanilla.chat", ChannelID: "222"},
		{Source: "mts.*", ChannelID: "333"},
	}
	if err := UpdateRoutesFile(path, newRoutes); err != nil {
		t.Fatalf("UpdateRoutesFile: %v", err)
	}

	// Set up the env vars Load needs to succeed, then reload and confirm the new routes
	// stuck.
	t.Setenv("FACTORIO_RCON_PASSWORD", "pw")
	t.Setenv("DISCORD_BOT_TOKEN", "tok")
	c, err := Load(path)
	if err != nil {
		t.Fatalf("reload after persist: %v", err)
	}
	if len(c.Discord.Routes) != 2 {
		t.Fatalf("routes: %+v", c.Discord.Routes)
	}
	if c.Discord.Routes[0].Source != "vanilla.chat" || c.Discord.Routes[0].ChannelID != "222" {
		t.Errorf("route[0]: %+v", c.Discord.Routes[0])
	}
	if c.Discord.Routes[1].Source != "mts.*" || c.Discord.Routes[1].ChannelID != "333" {
		t.Errorf("route[1]: %+v", c.Discord.Routes[1])
	}

	// Everything else in the file (comments, other keys) should be left alone — spot-check
	// a few fields that a naive "re-marshal the whole struct" approach would have altered.
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read persisted file: %v", err)
	}
	got := string(b)
	for _, want := range []string{
		"# Generated by the Open Discord Bridge setup wizard.",
		"address: game:27015",
		"trigger: \"!players\"",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("persisted file lost unrelated content %q\n---\n%s", want, got)
		}
	}
	if strings.Contains(got, `channel_id: "111"`) {
		t.Errorf("old route channel_id 111 should have been replaced:\n%s", got)
	}
}

// TestUpdateRoutesFileMissingFile covers the error path: a bad path should fail cleanly
// rather than silently no-op (so setConfig can log/report the persistence failure).
func TestUpdateRoutesFileMissingFile(t *testing.T) {
	if err := UpdateRoutesFile("/no/such/dir/bridge.yaml", []Route{{Source: "*", ChannelID: "1"}}); err == nil {
		t.Fatal("want error for a missing file")
	}
}

// TestLoadSetsFilePath covers the FilePath tracking that setConfig relies on to decide
// whether persistence is even possible (file-based vs. env-var config mode).
func TestLoadSetsFilePath(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "bridge.yaml")
	minimal := `factorio:
  rcon:
    address: game:27015
    password_env: FACTORIO_RCON_PASSWORD
  events_file: /tmp/events.jsonl
discord:
  token_env: DISCORD_BOT_TOKEN
  routes:
    - source: "*"
      channel_id: "1"
`
	if err := os.WriteFile(path, []byte(minimal), 0644); err != nil {
		t.Fatalf("write config: %v", err)
	}
	t.Setenv("FACTORIO_RCON_PASSWORD", "pw")
	t.Setenv("DISCORD_BOT_TOKEN", "tok")

	c, err := Load(path)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if c.FilePath != path {
		t.Errorf("FilePath = %q, want %q", c.FilePath, path)
	}

	// Env-var mode (no file) must leave FilePath empty — that's how setConfig knows
	// persistence isn't possible.
	t.Setenv("ODB_RCON_ADDRESS", "game:27015")
	t.Setenv("ODB_EVENTS_FILE", "/tmp/events.jsonl")
	t.Setenv("ODB_DISCORD_CHANNEL_ID", "1")
	envCfg, err := Load(filepath.Join(dir, "does-not-exist.yaml"))
	if err != nil {
		t.Fatalf("env load: %v", err)
	}
	if envCfg.FilePath != "" {
		t.Errorf("env-var mode FilePath = %q, want empty", envCfg.FilePath)
	}
}
