package wizard

import (
	"strings"
	"text/template"
)

// ConfigParams are the values the wizard collects to render a minimal bridge.yaml.
// Transport "" defaults to "local". SFTP* fields are only used when Transport == "sftp".
type ConfigParams struct {
	Transport   string // "local" (default) or "sftp"
	RconAddress string
	EventsFile  string
	GuildID     string
	ChannelID   string

	// SFTP-only:
	SFTPHost       string
	SFTPUser       string
	SFTPKeyPath    string // private key path; empty means password auth via SFTP_PASSWORD
	SFTPKnownHosts string // host-key file; empty skips host-key check (bridge logs a warning)
}

var configTmpl = template.Must(template.New("bridge.yaml").Parse(
	`# Generated by the Open Discord Bridge setup wizard.
# Secrets (token, RCON password{{if and (eq .Transport "sftp") (eq .SFTPKeyPath "")}}, SFTP password{{end}}) live in .env, referenced by *_env below.
factorio:
  rcon:
    address: {{.RconAddress}}
    password_env: FACTORIO_RCON_PASSWORD
  events_file: {{.EventsFile}}{{if eq .Transport "sftp"}}
  sftp:
    host: {{.SFTPHost}}
    user: {{.SFTPUser}}
    {{if .SFTPKeyPath}}key_path: {{.SFTPKeyPath}}{{else}}password_env: SFTP_PASSWORD{{end}}
    known_hosts_path: {{if .SFTPKnownHosts}}{{.SFTPKnownHosts}}{{else}}""{{end}}{{end}}

transport: {{.Transport}}
poll_interval: {{if eq .Transport "sftp"}}2s{{else}}1s{{end}}

discord:
  token_env: DISCORD_BOT_TOKEN
  guild_id: "{{.GuildID}}"
  routes:
    - source: "*"
      channel_id: "{{.ChannelID}}"
  commands:
    - trigger: "!players"
      rcon: "/players online"
`))

// RenderBridgeYAML produces a minimal, valid bridge.yaml from the collected params.
func RenderBridgeYAML(p ConfigParams) (string, error) {
	if p.Transport == "" {
		p.Transport = "local"
	}
	var b strings.Builder
	if err := configTmpl.Execute(&b, p); err != nil {
		return "", err
	}
	return b.String(), nil
}
