package wizard

import (
	"strings"
	"text/template"
)

// ConfigParams are the values the wizard collects to render a minimal bridge.yaml.
type ConfigParams struct {
	RconAddress string
	EventsFile  string
	GuildID     string
	ChannelID   string
}

var configTmpl = template.Must(template.New("bridge.yaml").Parse(
	`# Generated by the Open Discord Bridge setup wizard.
# Secrets (token, RCON password) live in .env, referenced by *_env below.
factorio:
  rcon:
    address: {{.RconAddress}}
    password_env: FACTORIO_RCON_PASSWORD
  events_file: {{.EventsFile}}

transport: local
poll_interval: 1s

discord:
  token_env: DISCORD_BOT_TOKEN
  guild_id: "{{.GuildID}}"
  routes:
    - source: "*"
      channel_id: "{{.ChannelID}}"
  commands:
    - trigger: "!players"
      rcon: "/players online"
`))

// RenderBridgeYAML produces a minimal, valid bridge.yaml from the collected params.
func RenderBridgeYAML(p ConfigParams) (string, error) {
	var b strings.Builder
	if err := configTmpl.Execute(&b, p); err != nil {
		return "", err
	}
	return b.String(), nil
}
